name: Mirror Repository

on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        ref: 'repo'

    - name: Sync with source repository
      run: |
        git remote add source https://github.com/IntersectMBO/cardano-haskell-packages.git
        git fetch source
        git reset --hard source/repo
        git push origin repo

